import localFont from "next/font/local";
import { Bebas_Neue, Montserrat, Kumbh_Sans } from 'next/font/google';
import "./globals.css";


const bebas = Bebas_Neue({ weight: '400', variable: "--font-bebas_neue", subsets: ["latin"] })
const kumbh = Kumbh_Sans({
  weights: ['400', '500', '600', '700', '800', '900'], // Make sure this font supports these weights
  variable: "--font-Kumbh_Sans",
  subsets: ["latin"]
})

const montserrat = Montserrat({ weight: ['400', '500', '600', '700', '800', '900'], variable: "--font-montserrat", subsets: ["latin"] })

const baron = localFont({
  src: "../../public/Baron_Kuffner.otf",
  weight: "100 400 700 900",
  variable: "--font-baron"
});
const helvetica = localFont({
  src: "../../public/Helvetica-Bold.ttf",
  weight: "400 700",
  variable: "--font-helvetica"
});
const cheesburga = localFont({
  src: "../../public/CHEESEBURGA.ttf",
  weight: "400",
  variable: "--font-CHEESEBURGA"
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${baron.variable} ${bebas.variable} ${helvetica.variable} ${montserrat.variable} ${cheesburga.variable} ${kumbh.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
