import localFont from "next/font/local";
import { Bebas_Neue, Montserrat } from 'next/font/google';
import "./globals.css";


const bebas = Bebas_Neue({ weight: '400', variable: "--font-bebas_neue", subsets: ["latin"] })

const montserrat = Montserrat({ weight: '700', variable: "--font-montserrat", subsets: ["latin"] })

const baron = localFont({
  src: "../../public/Baron_Kuffner.otf",
  weight: "100 400 700 900",
  variable: "--font-baron"
});
const cheesburga = localFont({
  src: "../../public/CHEESEBURGA.ttf",
  weight: "400",
  variable: "--font-CHEESEBURGA"
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${baron.variable} ${bebas.variable} ${montserrat.variable} ${cheesburga.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
